
processing:
   >>>  input==> future_test1.py
   >>> saveAs==> future_test1.1124_231848.py
   >>> output==> future_test1.py

Traceback (most recent call last):
  File "/Users/klaus/.env/bin/addend", line 8, in <module>
    sys.exit(main())
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/command_line.py", line 4, in main
    addend.main()
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 911, in main
    type, data, cache = classify_lines(pydata)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 461, in classify_lines
    index = testMLComment(data, type, index)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 272, in testMLComment
    lineHasMLC = MLC_regex.search(data[index])
IndexError: list index out of range

processing:
   >>>  input==> future_test1.py
   >>> saveAs==> future_test1.1124_231849.py
   >>> output==> future_test1.py


   done: original input file saved as 'future_test1.1124_231849.py'

5a6
> 
8a10
> 
10a13
> 

processing:
   >>>  input==> future_test1.py
   >>> output==> new.future_test1.py

Traceback (most recent call last):
  File "/Users/klaus/.env/bin/addend", line 8, in <module>
    sys.exit(main())
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/command_line.py", line 4, in main
    addend.main()
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 911, in main
    type, data, cache = classify_lines(pydata)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 461, in classify_lines
    index = testMLComment(data, type, index)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 272, in testMLComment
    lineHasMLC = MLC_regex.search(data[index])
IndexError: list index out of range
