
processing:
   >>>  input==> sample_doctest.py
   >>> saveAs==> sample_doctest.1126_001316.py
   >>> output==> sample_doctest.py

Traceback (most recent call last):
  File "/Users/klaus/.env/bin/addend", line 8, in <module>
    sys.exit(main())
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/command_line.py", line 4, in main
    addend.main()
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 953, in main
    type, data, cache = classify_lines(pydata)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 498, in classify_lines
    index = testMLComment(data, type, index)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 289, in testMLComment
    lineHas1Ldq = MLC1Ldq_regex.search(data[index])
IndexError: list index out of range

processing:
   >>>  input==> sample_doctest.py
   >>> saveAs==> sample_doctest.1126_001316.py
   >>> output==> sample_doctest.py


   done: original input file saved as 'sample_doctest.1126_001316.py'


processing:
   >>>  input==> sample_doctest.py
   >>> output==> new.sample_doctest.py

Traceback (most recent call last):
  File "/Users/klaus/.env/bin/addend", line 8, in <module>
    sys.exit(main())
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/command_line.py", line 4, in main
    addend.main()
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 953, in main
    type, data, cache = classify_lines(pydata)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 498, in classify_lines
    index = testMLComment(data, type, index)
  File "/Users/klaus/.env/lib/python3.9/site-packages/addend/addend.py", line 289, in testMLComment
    lineHas1Ldq = MLC1Ldq_regex.search(data[index])
IndexError: list index out of range
